CREATE TABLE MEMBER
(
    EMAIL VARCHAR2 (40) PRIMARY KEY,
    NICKNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2 (150) NOT NULL,
    PHONE VARCHAR2 (30),
    NAVERLOGIN VARCHAR2(30),
    KAKAOLOGIN VARCHAR2(30),

    
)